/*
 * Color Pong for Tang Nano 4K (GW1NSR-4C) - PSRAM RGB888 framebuffer.
 *
 * 架构:
 *   Cortex-M3 以 128 字节 (32 词) 块为单位, 经 APB2 桥把合成好的 RGB888
 *   像素写入板载 HyperRAM 帧缓冲 (640x480, 每行 1920 字节 = 15 块);
 *   fabric 读引擎持续把整帧经 HDMI 输出 (640x480@60 全彩)。
 *
 * 渲染模型 (与旧单色版相同的 "compose" 思想):
 *   每个块的内容 = compose(背景 + 当前物体), 擦除 = 用当前状态重写旧区域,
 *   因此显示端永远读不到 "擦了一半" 的中间态。
 *   背景是静态的魂斗罗风格场景: 日落渐变天空 + 星星 + 两层山峦剪影 +
 *   丛林地面 + 中场虚线, 全部整数运算按坐标即时合成。
 *   物体 (按优先级): 球 > 比分数字 > 球拍 > 背景。
 *
 * 小球与两块挡板改由 fabric 在像素通路上实时叠加 (top.v 的 spr_px): M3 每帧
 * 只写 4 个位置寄存器 (0x40/0x44/0x48/0x4C), 不再往帧缓冲里画它们。
 * 物体的运动因此完全脱离 HyperRAM 写通道 (每帧只有垂直消隐期一个写窗口,
 * 每个窗口只能推出几十个 128 字节块) 的限制, 可以做到真正的 60fps 平滑运动,
 * 速度也能自由提高而不再拖慢画面。
 * 帧缓冲里只剩静态内容, 每帧只重写 "脏区域" 的块:
 *   数字: 仅比分变化 / 终局闪烁时
 *   诊断: 仅状态翻转时
 *
 * 控制: KEY1 上移 / KEY2 下移 / KEY3 重置
 * 规则: 先得 15 分者胜, 球停止, 比分闪烁
 */
#include "gw1ns4c.h"
#include "delay.h"

/* ------------------------------------------------------------------ */
/* DIAGNOSTIC SWITCH (bisect the fault space in ONE flash)             */
/*                                                                     */
/* 0 = normal game.                                                    */
/*                                                                     */
/* 1 = STATIC TEST: boot exactly as the game does (full scene composed */
/*     into BOTH framebuffers), then run ONLY the double-buffer swap    */
/*     loop with NO framebuffer writes at all - no keys, no game_tick, */
/*     no render().                                                    */
/*                                                                     */
/*     This is the one experiment the memory-independent test pattern  */
/*     could NOT do: it exercises the HyperRAM read engine, the async  */
/*     video FIFO, the read-revolution base switch and the CDC into    */
/*     the pixel domain, but with ZERO M3 write traffic.               */
/*                                                                     */
/*       picture rock-steady, clean  -> read engine / FIFO / swap /    */
/*                                      pixel CDC are all fine with    */
/*                                      no write traffic, so the       */
/*                                      corruption is caused by the M3 */
/*                                      WRITE traffic itself (APB CDC, */
/*                                      bus arbitration, or writing the */
/*                                      buffer being scanned out).     */
/*       picture still striped or    -> the corruption is in the read  */
/*       flickering                     / FIFO / swap path itself.     */
/*                                                                     */
/*     The two 16x8 corner blocks are still generated by the fabric,   */
/*     so the FIFO-water and read-timeout indicators keep working.     */
#define STATIC_TEST 0

/* SECOND DIAGNOSTIC: BLOCK_COLOUR_BARS.
   With STATIC_TEST the framebuffer content is only whatever the boot-time
   draw produced, so to find out whether the memory/read path preserves a
   BLOCK (128 bytes = 42.67 px) intact, fill the frame with 15 SOLID vertical
   bars - one per block column - using the exact same compose + fb_block path
   the game uses, then freeze it. Colours are unambiguous primaries/secondaries.
   Read the bars left to right and compare with the list below:
       correct : R G B Y C M W grey drkR drkG drkB olive teal purple lgrey
   A rotated/shifted colour in bar k means the byte phase is wrong for that
   block; the thin mixed line at every bar edge is EXPECTED (128 bytes is not
   a whole number of pixels, so the boundary pixel gets its R from one block
   and its G,B from the next). */
#define BLOCK_COLOUR_BARS 0

static const uint32_t blk_palette[15] = {
    0xFF0000u,  /* R  */
    0x00FF00u,  /* G  */
    0x0000FFu,  /* B  */
    0xFFFF00u,  /* Y  */
    0x00FFFFu,  /* C  */
    0xFF00FFu,  /* M  */
    0xFFFFFFu,  /* W  */
    0x808080u,  /* grey */
    0x800000u,  /* dark R */
    0x008000u,  /* dark G */
    0x000080u,  /* dark B */
    0x808000u,  /* olive  */
    0x008080u,  /* teal   */
    0x800080u,  /* purple */
    0xC0C0C0u   /* light grey */
};

/* ------------------------------------------------------------------ */
/* APB2 register map (matches apb_pong_reg.v)                          */
/* ------------------------------------------------------------------ */
#define PONG_APB_BASE   (APB2MASTER1_BASE)   /* 0x40002400 */

#define REG_KEY         0x04    /* RO keys (pressed = 0)                */
#define REG_HP          0x08    /* RO bit0 = HyperRAM init_calib done   */
#define REG_FRAME       0x0C    /* RO [7:0] display frame counter       */
#define REG_FB_BLK      0x24    /* WO [12:0] 128-byte block index       */
#define REG_FB_DATA     0x28    /* WO framebuffer word (toggles req)    */
#define REG_FB_STATUS   0x2C    /* RO bit0 = ack sync                   */
#define REG_BUF_SWAP    0x30    /* WO toggles: request framebuffer flip */
#define REG_BUF_DISP    0x34    /* RO bit0 = displayed framebuffer 0/1  */
#define REG_FB_READY    0x38    /* WO toggles: first whole frame is up  */
#define REG_P1_Y        0x40    /* WO [9:0] P1 paddle top row (overlay) */
#define REG_P2_Y        0x44    /* WO [9:0] P2 paddle top row (overlay) */
#define REG_BALL_X      0x48    /* WO [9:0] ball centre x     (overlay) */
#define REG_BALL_Y      0x4C    /* WO [9:0] ball centre y     (overlay) */

/* Bit map measured on hardware with the eight-square monitor drawn by
   obj_pixel() (square 1 = bit 0, numbered from the left). The two direction
   keys were still inverted on the bench - the key the user calls "up" moved the
   paddle DOWN - so the pair is SWAPPED relative to the first measurement: bit 1
   now drives the paddle UP, bit 2 drives it DOWN. If the directions ever come
   out reversed again, this pair is the only thing to flip.
   KEY_RESET (bit 0) has not been measured yet - press the reset key and read
   which square turns red, then narrow this mask the same way. */
#define KEY_UP          ((1u << 1))
#define KEY_DOWN        ((1u << 2))
#define KEY_RESET       ((1u << 0))   /* unmeasured */
#define KEY_PRESSED(k)  (((apb_read(REG_KEY) & (k)) != (k)))

/* ------------------------------------------------------------------ */
/* Screen / framebuffer geometry                                       */
/*   640x480 RGB888: row = 1920 bytes = 15 blocks of 128 bytes;        */
/*   frame = 921600 bytes = 230400 words = 7200 blocks.                */
/* ------------------------------------------------------------------ */
#define HOR_PIXELS      640
#define VER_PIXELS      480
#define BLOCKS_PER_ROW  15
#define FRAME_BLOCKS    7200

/* Object geometry. These are MIRRORED in top.v's spr_px() (the fabric draws
   the ball and the paddles), so the two must be changed together:
   PADDLE_W 10 @ P1_X 10 -> x 10..19, highlight on x >= 18
   PADDLE_W 10 @ P2_X 620 -> x 620..629, highlight on x < 622
   PADDLE_H 100, BALL_HALF 6 (13x13). Only PADDLE_H is still needed here. */
#define PADDLE_W        10
#define PADDLE_H        100
#define PADDLE_MAX      (VER_PIXELS - PADDLE_H - 2)    /* 378 */
#define P1_X            10
#define P2_X            (HOR_PIXELS - 20)              /* 620 */
#define BALL_HALF       6                              /* ball = 13x13 px */

#define GROUND_Y        400

/* Score digits: 5x3 font scaled x8 -> 25x41 px each, top center */
#define DIGIT_SCALE     8
#define DIGIT_W         (3 * DIGIT_SCALE + 1)          /* 25 */
#define DIGIT_H         (5 * DIGIT_SCALE + 1)          /* 41 */
#define DIGIT_Y         12
static const int32_t digit_x[4] = { 196, 236, 380, 420 };

/* Speed parameters (same physics as the monochrome version) */
/* The paddles are drawn by the fabric overlay now, so the M3 pays no HyperRAM
   write at all for them: these are pure speed knobs at a steady 60 Hz.
   With the hardware overlay the SMOOTHNESS is decided solely by how many
   pixels an object moves per frame: a step larger than the object itself
   (paddle 10 px wide) reads as a jump, not as motion. Keep the steps small.
   (5 -> 300 px/s: the AI now steps at the same per-frame rate as the player,
   but it is still weaker than P1 because it only REACTS with a 40 px dead
   zone and never predicts - see AI_REACT_X below). */
#define P1_STEP         5
#define AI_STEP         5
/* The ball is a fabric overlay too, so its speed costs nothing per frame and
   TICKS_PER_RENDER stays 1 (exactly one physics step per 60 Hz frame, paced by
   the framebuffer flip in the main loop). game_tick()'s own <=4 px sub-stepping
   still samples the paddle window on every intermediate pixel, so the ball
   cannot tunnel through a paddle even when |vx| is raised a lot.
   The ball is NOT constant-speed: it starts at BALL_VX0/VY0 and every wall or
   paddle bounce makes the rally faster (see ball_speed_up), saturating at
   MAX_VX/MAX_VY. */
#define TICKS_PER_RENDER 1
#define BALL_VX0        2
#define BALL_VY0        2
#define MAX_VX          9
#define MAX_VY          5
/* The AI starts tracking the ball once it crosses this x (moving right).
   It used to be HOR_PIXELS-30 = 610, i.e. only 10 px from the AI paddle at
   x=620: at vx=2..9 the ball covered that in 1..5 frames, so even at a full
   step the AI could move at most ~25 px and looked frozen. Starting at
   HOR_PIXELS-160 = 480 gives it 140 px of travel time, so it visibly tracks
   and is still beatable (40 px dead zone + no prediction + it can be faked
   by a wall bounce after it commits). */
#define AI_REACT_X      (HOR_PIXELS - 160)
/* After a goal the ball is parked off-screen for this many frames. The score
   repaint (a burst of block writes through the vblank-only HyperRAM window)
   stalls the M3 for a frame or two; parking the ball makes that stall
   invisible and reads as an intentional breather before the next serve. */
#define RESPAWN_FRAMES  40

/* ------------------------------------------------------------------ */
/* Palette. The four object colours below are now used by the FABRIC overlay
   (top.v SPR_P1/SPR_P2/SPR_BALL, byte-swapped); they are kept here as the
   single source of truth. Only COL_DIGIT is still used in C. */
/* ------------------------------------------------------------------ */
#define COL_P1          0x00C8FFu   /* cyan paddle              */
#define COL_P1_HI       0x96F0FFu   /* cyan highlight edge      */
#define COL_P2          0xFF5A1Eu   /* orange-red paddle        */
#define COL_P2_HI       0xFFC896u   /* orange highlight edge    */
#define COL_BALL        0xFFF08Cu   /* warm bright ball         */
#define COL_DIGIT       0xFFD200u   /* yellow score             */
#define COL_DIGIT_DIM   0x40320Au   /* dim score (blink off)    */

static inline uint32_t apb_read(uint32_t off)
{
    return *(volatile uint32_t *)(PONG_APB_BASE + off);
}

static inline void apb_write(uint32_t off, uint32_t val)
{
    *(volatile uint32_t *)(PONG_APB_BASE + off) = val;
}

/* ------------------------------------------------------------------ */
/* Framebuffer block write (LEVEL handshake, see apb_pong_reg.v)       */
/*   write FB_BLK once, then exactly 32 words with per-word ack wait.  */
/* ------------------------------------------------------------------ */
static uint32_t fb_req_expected;

static inline void fb_word(uint32_t data)
{
    uint32_t timeout;
    fb_req_expected ^= 1u;
    apb_write(REG_FB_DATA, data);
    timeout = 0x200000u;
    while (((apb_read(REG_FB_STATUS) & 1u) != fb_req_expected) && --timeout)
        ;
}

/* Write one composed 128-byte block (buf = 128 bytes, MSB-first words). */
static void fb_block(uint32_t blk, const uint8_t *buf)
{
    int32_t k;
    apb_write(REG_FB_BLK, blk);
    for (k = 0; k < 32; k++) {
        uint32_t w = ((uint32_t)buf[4*k]   << 24) |
                     ((uint32_t)buf[4*k+1] << 16) |
                     ((uint32_t)buf[4*k+2] <<  8) |
                     ((uint32_t)buf[4*k+3]);
        fb_word(w);
    }
}

/* ------------------------------------------------------------------ */
/* Object model                                                        */
/* ------------------------------------------------------------------ */
static int32_t p1_pos, p2_pos;
static int32_t ball_x, ball_y;
static int32_t vx, vy;
static int32_t s1, s2;
static int32_t game_over;
static int32_t digit_dim;               /* blink phase: digits dimmed   */
static int32_t rally;                   /* bounces in the current rally      */
static int32_t respawn_wait;            /* frames left before the next serve */
static int32_t serve_dir = 1;           /* +1 = serve right, -1 = serve left */

/* Last-rendered object state, one set PER FRAMEBUFFER (double buffering).
   Buffer r is rendered every other frame, so when we render into it its
   content is two frames old - erasing must be based on the state stored when
   that same buffer was last drawn, not on the other buffer.
   The sentinels force a full object redraw the first time each buffer is
   rendered; game_reset() deliberately does NOT re-arm them, because the
   objects still have to be erased from the stored positions. */
static int32_t old_s1[2] = { -1, -1 }, old_s2[2] = { -1, -1 };
static int32_t old_dim[2] = { -1, -1 };

/* 5x3 font, column-major, bit (row + col*5) - same as the old design */
static const uint16_t font5x3[10] = {
    0x7E3F, 0x03E0, 0x5EBD, 0x7EB5, 0x7C87,
    0x76B7, 0x76BF, 0x7C21, 0x7EBF, 0x7EB7
};

/* ------------------------------------------------------------------ */
/* On-screen test squares REMOVED                                      */
/* ------------------------------------------------------------------ */
/* The framebuffer-flip health square and the eight key-bit monitor squares
   that used to be baked into the framebuffer are gone, together with the
   fabric's two corner patches (top.v), so the playfield is clean. flip_miss is
   still counted so a broken flip degrades the pacing instead of stalling the
   game (see wait_disp/wait_frame); nothing is drawn from it any more. */
static uint32_t flip_miss;                        /* count of timed-out flips */

/* ------------------------------------------------------------------ */
/* Background synthesis (integer math only)                            */
/* ------------------------------------------------------------------ */
/* triangle wave: 0..amp, period p */
static int32_t tri(int32_t x, int32_t p, int32_t amp)
{
    int32_t h = p / 2;
    int32_t m = x % p;
    int32_t t = (m < h) ? m : (p - m);
    return (t * amp) / h;
}

/* The two mountain ridges depend ONLY on x, yet the old bg_pixel() evaluated
   four tri() calls - four software divisions plus four modulo ops - for EVERY
   pixel of EVERY row (640*480 = 307200 times). The Cortex-M3 has no divide
   instruction, so that single loop dominated compose_block() and capped the
   game loop at roughly 12 blocks per vblank write window - which is exactly
   why both the ball and the paddle felt slow: the physics advances once per
   completed render, and a render only got ~12 blocks per frame through the
   write channel. Both ridge sums are tabulated once at startup now, so the
   per-pixel cost collapses to two byte loads. The sums are 0..70 and 0..62,
   so int8_t is ample.
   NOTE: the three hash-based per-pixel textures (grass-edge brightness,
   ground speckle, sky star field) are still REMOVED - re-adding any of them
   brings back the "electric interference" speckle. */
static int8_t ridge_near[HOR_PIXELS];   /* tri(x,150,60) + tri(x,47,10) */
static int8_t ridge_far [HOR_PIXELS];   /* tri(x,220,50) + tri(x,73,12) */

static void bg_init(void)
{
    int32_t x;
    for (x = 0; x < HOR_PIXELS; x++) {
        ridge_near[x] = (int8_t)(tri(x, 150, 60) + tri(x, 47, 10));
        ridge_far [x] = (int8_t)(tri(x, 220, 50) + tri(x, 73, 12));
    }
}

/* The sky gradient and the jungle-ground shading depend ONLY on y as well, and
   used to cost three more divisions per PIXEL. They are computed once per ROW
   here (bg_row() is called at the top of compose_block), and bg_pixel() then
   just reads the cached colour. */
static int32_t  bg_row_y = -1;
static int      row_ground;      /* 1 = this row is at/below GROUND_Y */
static int      row_grass;       /* 1 = grass-edge band               */
static uint32_t row_ground_rgb;  /* shaded jungle ground              */
static uint32_t row_sky_rgb;     /* sunset gradient                   */

#define COL_GRASS  (((uint32_t)(180u >> 3) << 16) | (180u << 8) | 0x28u)

static void bg_row(int32_t y)
{
    if (y == bg_row_y)
        return;
    bg_row_y = y;

    if (y >= GROUND_Y) {
        row_ground = 1;
        row_grass  = (y < GROUND_Y + 6);
        if (!row_grass) {
            int32_t d = y - GROUND_Y - 6;
            int32_t g = 100 - d;
            if (g < 32) g = 32;
            row_ground_rgb = (0x0Fu << 16) | ((uint32_t)g << 8) | 0x16u;
        }
    } else {
        uint32_t r, g, b;
        row_ground = 0;
        row_grass  = 0;
        r = 10u + (uint32_t)(190 * y) / 400u;
        g = 8u  + (uint32_t)(70 * y) / 400u;
        b = 50u - (uint32_t)(10 * y) / 400u;
        if (y > 300) b += (uint32_t)(y - 300) / 4u;
        row_sky_rgb = (r << 16) | (g << 8) | b;
    }
}

static uint32_t bg_pixel(int32_t x, int32_t y)
{
    if (row_ground)
        return row_grass ? COL_GRASS : row_ground_rgb;

    /* sky: two mountain ridges in front of the cached sunset gradient */
    {
        int32_t yr2 = 300 + ridge_near[x];   /* near ridge */
        int32_t yr1 = 230 + ridge_far [x];   /* far  ridge */
        int32_t d;
        if (y >= yr2) {
            d = y - yr2; if (d > 14) d = 14;
            return ((uint32_t)(18 - (d >> 1)) << 16) |
                   ((uint32_t)(12 - (d >> 2)) << 8) | (uint32_t)(32 - (d >> 1));
        }
        if (y >= yr1) {
            d = y - yr1; if (d > 20) d = 20;
            return ((uint32_t)(35 - d) << 16) |
                   ((uint32_t)(20 - (d >> 1)) << 8) | (uint32_t)(55 - d);
        }
        return row_sky_rgb;
    }
}

/* ------------------------------------------------------------------ */
/* Foreground objects BAKED INTO the framebuffer (digits + diagnostics). */
/* The ball and the paddles are NOT here any more: they are overlaid by the
   fabric (top.v spr_px) from their position registers, so they must stay out
   of the memory image or they would be left behind as ghosts when they move. */
/* Returns 1 and *rgb when an object covers (x,y), else 0.             */
/* ------------------------------------------------------------------ */
static int32_t obj_pixel(int32_t x, int32_t y, uint32_t *rgb)
{
    /* score digits */
    if (y >= DIGIT_Y && y < DIGIT_Y + DIGIT_H) {
        int32_t d;
        for (d = 0; d < 4; d++) {
            int32_t xoff = digit_x[d];
            if (x >= xoff && x < xoff + DIGIT_W) {
                int32_t val = (d == 0) ? s1 / 10 : (d == 1) ? s1 % 10 :
                              (d == 2) ? s2 / 10 : s2 % 10;
                int32_t row = (y - DIGIT_Y) / DIGIT_SCALE;
                int32_t col = (x - xoff) / DIGIT_SCALE;
                if (row < 5 && col < 3 &&
                    (font5x3[val] & (1u << (row + col * 5)))) {
                    *rgb = digit_dim ? COL_DIGIT_DIM : COL_DIGIT;
                    return 1;
                }
            }
        }
    }

    return 0;
}

/* ------------------------------------------------------------------ */
/* Compose one 128-byte block of row `y` (block column `kc`, 0..14)    */
/* Byte g (global) -> pixel x = g/3, channel = g%3 (0=R,1=G,2=B).      */
/* ------------------------------------------------------------------ */
static uint8_t blk_buf[128];

/* Memory byte order per pixel.
   top.v's pixel mux emits {grp[79:72], grp[87:80], grp[95:88]}, i.e. the
   first three bytes of the 32-bit word REVERSED; and the SVO stack binds
   bits[23:16] to the BLUE lane (proved by the test pattern: 0xFF0000 was
   displayed BLUE and yellow/cyan came out swapped). Reversal + BGR lane
   order cancel out, so a memory byte stream of plain [R,G,B] is displayed as
   [R,G,B]. The memory must therefore hold [R,G,B]: channel 0 -> >>16,
   1 -> >>8, 2 -> >>0. The previous { 8, 0, 16 } stored [G,B,R] and rotated
   every colour by one channel (cyan paddle -> yellow-green, yellow score ->
   violet) - that is the "colour stain", not a memory fault. */
static const uint8_t ch_shift[3] = { 16, 8, 0 };

static void compose_block(int32_t y, int32_t kc)
{
    int32_t g0 = kc * 128;
    int32_t x = g0 / 3;
    int32_t c = g0 % 3;
    int32_t j;
    uint32_t rgb = 0;

    bg_row(y);          /* cache the y-only background colours for this row */

    for (j = 0; j < 128; j++) {
        /* 128 bytes is not a whole number of pixels (128 = 42*3 + 2), so a
           block can start in the middle of a pixel (c = g0 % 3 != 0). In that
           case the first byte(s) belong to a pixel whose R was already written
           by the previous block - we must still evaluate it here, otherwise
           rgb stays 0 and the pixel's remaining channels render as 0 (dark
           specks at every block boundary). */
        if (c == 0 || j == 0) {
            /* new pixel: evaluate object first, else background */
            if (!obj_pixel(x, y, &rgb))
                rgb = bg_pixel(x, y);
        }
        blk_buf[j] = (uint8_t)((rgb >> ch_shift[c]) & 0xFFu);
        if (++c == 3) { c = 0; x++; }
    }
}

static void write_block(int32_t y, int32_t kc)
{
    compose_block(y, kc);
    fb_block((uint32_t)(y * BLOCKS_PER_ROW + kc), blk_buf);
}

/* Rewrite every block touched by rect (x1,y1)-(x2,y2) inclusive. */
static void fill_rect(int32_t x1, int32_t y1, int32_t x2, int32_t y2)
{
    int32_t kl, kr, k, y;

    if (x1 < 0) x1 = 0;
    if (y1 < 0) y1 = 0;
    if (x2 > HOR_PIXELS - 1) x2 = HOR_PIXELS - 1;
    if (y2 > VER_PIXELS - 1) y2 = VER_PIXELS - 1;
    if (x1 > x2 || y1 > y2) return;

    kl = (x1 * 3) >> 7;
    kr = ((x2 * 3 + 2) >> 7);
    if (kr > BLOCKS_PER_ROW - 1) kr = BLOCKS_PER_ROW - 1;

    for (y = y1; y <= y2; y++)
        for (k = kl; k <= kr; k++)
            write_block(y, k);
}

/* Full initial scene: compose every block (background + objects). */
static void draw_full_scene(void)
{
    int32_t y, k;
    for (y = 0; y < VER_PIXELS; y++)
        for (k = 0; k < BLOCKS_PER_ROW; k++)
            write_block(y, k);
}

/* Diagnostic: 15 solid vertical bars, one per block column, written through
   the SAME compose + fb_block path the game uses (see BLOCK_COLOUR_BARS). */
#if BLOCK_COLOUR_BARS
static void draw_block_pattern(void)
{
    int32_t y, kc, j;
    for (y = 0; y < VER_PIXELS; y++) {
        for (kc = 0; kc < BLOCKS_PER_ROW; kc++) {
            uint32_t rgb = blk_palette[kc];
            int32_t g0 = kc * 128;
            int32_t c  = g0 % 3;
            for (j = 0; j < 128; j++) {
                blk_buf[j] = (uint8_t)((rgb >> ch_shift[c]) & 0xFFu);
                if (++c == 3) c = 0;
            }
            fb_block((uint32_t)(y * BLOCKS_PER_ROW + kc), blk_buf);
        }
    }
}
#endif

/* ------------------------------------------------------------------ */
/* Dirty-region render into framebuffer `r` (0/1)                      */
/* ------------------------------------------------------------------ */
static void render(int32_t r)
{
    int32_t prev_s1 = old_s1[r], prev_s2 = old_s2[r], prev_dim = old_dim[r];

    /* The ball and the paddles are NOT written here any more - the fabric
       overlays them from the position registers (top.v spr_px), so moving
       them costs no HyperRAM write at all. Only the score digits are BAKED
       into the framebuffer, so they are all render() ever repaints. */

    /* digits: on score change or blink toggle */
    if (s1 != prev_s1 || s2 != prev_s2 || digit_dim != prev_dim) {
        int32_t d;
        for (d = 0; d < 4; d++) {
            int32_t val = (d == 0) ? s1 / 10 : (d == 1) ? s1 % 10 :
                          (d == 2) ? s2 / 10 : s2 % 10;
            int32_t pval = (d == 0) ? prev_s1 / 10 : (d == 1) ? prev_s1 % 10 :
                           (d == 2) ? prev_s2 / 10 : prev_s2 % 10;
            if (val != pval || digit_dim != prev_dim)
                fill_rect(digit_x[d], DIGIT_Y,
                          digit_x[d] + DIGIT_W - 1, DIGIT_Y + DIGIT_H - 1);
        }
        prev_s1 = s1; prev_s2 = s2; prev_dim = digit_dim;
    }

    old_s1[r] = prev_s1; old_s2[r] = prev_s2; old_dim[r] = prev_dim;
}

/* Prime BOTH buffers' dirty state from the current state, right after their
   initial full-scene draw, so the first delta render knows what is already
   baked into each buffer (score digits + diagnostics). */
static void sync_old_state(void)
{
    int32_t i;
    for (i = 0; i < 2; i++) {
        old_s1[i] = s1; old_s2[i] = s2; old_dim[i] = digit_dim;
    }
}

/* Request a framebuffer flip (takes effect at the next frame boundary). */
static void buf_swap_request(void)
{
    apb_write(REG_BUF_SWAP, 1u);
}

/* Wait for the fabric to scan out buffer `r`. Returns 1 when the flip landed,
   0 when it did not.

   The bound is counted in DISPLAY FRAMES taken from the fabric's own 60 Hz
   counter, NOT in loop iterations. The previous version spanned 0x800000
   iterations, which is ~3 s at 27 MHz: one lost flip therefore froze the whole
   game for seconds, and that single stall is what looked like "the left paddle
   never sweeps", "the keys only react after a while" and "the ball is slow".
   Three frames is 50 ms, so a lost flip now costs one frame, not three seconds.

   Note this does NOT make the firmware tolerant of a half-written buffer: the
   bound only shortens the wait, it never lets the loop run ahead of the flip
   in the normal case, because a landing flip returns immediately. */
static int32_t wait_disp(int32_t r)
{
    uint32_t f0 = apb_read(REG_FRAME) & 0xFFu;
    for (;;) {
        if ((int32_t)(apb_read(REG_BUF_DISP) & 1u) == r)
            return 1;
        if (((apb_read(REG_FRAME) & 0xFFu) - f0) >= 3u)
            return 0;
    }
}

/* Fallback pacing on the fabric's own frame counter, used ONLY when the flip
   did not land, so a broken flip degrades the update rate instead of stalling
   the game. In the healthy case this is never called and the loop stays paced
   by wait_disp() exactly as before. */
static void wait_frame(void)
{
    uint32_t f0 = apb_read(REG_FRAME) & 0xFFu;
    while (((apb_read(REG_FRAME) & 0xFFu) == f0))
        ;
}

/* ------------------------------------------------------------------ */
/* Game logic (same physics as the monochrome version)                 */
/* ------------------------------------------------------------------ */
static void game_reset(void)
{
    p1_pos = 190;
    p2_pos = 190;
    ball_x = 320;
    ball_y = 240;
    vx = BALL_VX0;
    vy = BALL_VY0;
    s1 = 0;
    s2 = 0;
    game_over = 0;
    digit_dim = 0;
    rally = 0;
    respawn_wait = 0;
    serve_dir = 1;
}

/* Every wall or paddle bounce makes the rally a little faster: the speed
   magnitude is derived from the rally length, so the ball starts at
   BALL_VX0/VY0 and accelerates towards MAX_VX/MAX_VY instead of running at a
   constant speed. Call it AFTER mirroring the direction, so the sign is
   already correct when the magnitude is written back. */
static void ball_speed_up(void)
{
    int32_t m;
    /* Half a px per bounce horizontally and a quarter px vertically, so the
       ramp takes about twice as many bounces to reach MAX_VX/MAX_VY as the
       earlier full-speed-per-bounce version did. */
    if (rally < 63) rally++;
    m = BALL_VX0 + (rally >> 1);          /* horizontal ramp */
    if (m > MAX_VX) m = MAX_VX;
    vx = (vx < 0) ? -m : m;
    m = BALL_VY0 + (rally >> 2);          /* vertical ramp */
    if (m > MAX_VY) m = MAX_VY;
    vy = (vy < 0) ? -m : m;
}

static void game_tick(void)
{
    if (respawn_wait > 0) {
        /* Parked off-screen between points. The score repaint is performed
           during this pause (it blocks the loop for a frame or two on the
           vblank-only write window), so that stall is invisible. */
        if (--respawn_wait == 0) {
            rally = 0;
            ball_x = 320;
            ball_y = 240;
            vx = (serve_dir > 0) ? BALL_VX0 : -BALL_VX0;
            vy = BALL_VY0;
        }
        return;
    }
    if (game_over)
        return;                 /* ball stops, score blinks */

    /* Vertical motion first: |vy| <= MAX_VY is small and the paddle window is
       105 px tall, so one step cannot tunnel through it vertically. */
    ball_y += vy;

    /* top / bottom walls: mirror about the BALL'S EDGE (the hardware sprite is
       13 px tall, i.e. ball_y +/- BALL_HALF), so the whole ball stays on
       screen. The old 5 / 474 limits let the sprite span rows -1..480,
       clipping one row at the top and one at the bottom. */
    if (ball_y < BALL_HALF) {
        ball_y = 2 * BALL_HALF - ball_y;
        vy = -vy;
        ball_speed_up();
    }
    if (ball_y > VER_PIXELS - 1 - BALL_HALF) {
        ball_y = 2 * (VER_PIXELS - 1 - BALL_HALF) - ball_y;
        vy = -vy;
        ball_speed_up();
    }

    /* Horizontal motion in sub-steps of at most 4 px. The paddle hit window is
       only 16 px wide (5 < x < 22), so a single MAX_VX=26 step used to jump
       clean over the paddle and the ball passed straight through it. Sampling
       every <=4 px guarantees several samples inside the window at any speed
       up to roughly 4x this one, so the paddles keep working when vx grows. */
    {
        int32_t remain = vx;
        while (remain != 0) {
            int32_t step = remain;
            if (step >  4) step =  4;
            if (step < -4) step = -4;
            ball_x += step;
            remain -= step;

            /* paddle hits: mirror about the paddle edge and speed up (|vx| + 1) */
            if (vx < 0 && ball_x > 5 && ball_x < 22 &&
                ball_y > p1_pos - 5 && ball_y < p1_pos + 105) {
                ball_x = 44 - ball_x;
                vx = -vx;
                ball_speed_up();
                break;
            }
            if (vx > 0 && ball_x > 617 && ball_x < 634 &&
                ball_y > p2_pos - 5 && ball_y < p2_pos + 105) {
                ball_x = 1234 - ball_x;
                vx = -vx;
                ball_speed_up();
                break;
            }
            if (ball_x < 5 || ball_x > 634)
                break;                          /* goal line reached */
        }
    }

    /* goals: park the ball off-screen, serve again after a short breather.
       The pause also hides the score repaint, which is a burst of block writes
       through the vblank-only HyperRAM window and stalls the M3 for a frame. */
    if (ball_x < 5) {
        s2++;
        if (s2 >= 15) {
            game_over = 1;
        } else {
            ball_x = 700; ball_y = 700;     /* off-screen, not drawn */
            rally = 0;
            serve_dir = -serve_dir;
            respawn_wait = RESPAWN_FRAMES;
        }
    } else if (ball_x > 634) {
        s1++;
        if (s1 >= 15) {
            game_over = 1;
        } else {
            ball_x = 700; ball_y = 700;     /* off-screen, not drawn */
            rally = 0;
            serve_dir = -serve_dir;
            respawn_wait = RESPAWN_FRAMES;
        }
    }
}

int main(void)
{
    uint32_t blink_cnt = 0;
    uint32_t prev_keys = 0xFFFFFFFFu;
    uint32_t reset_hold = 0;
    int32_t  r;                         /* framebuffer we render into next */

    delay_init();
    delay_ms(10);

    /* wait for HyperRAM calibration before touching the framebuffer */
    while (!(apb_read(REG_HP) & 1u))
        ;

    /* Double buffer init: fill the off-screen buffer, flip to it (the screen
       now shows a complete scene), then fill the other one while it is being
       displayed. Both framebuffers end up holding the full initial scene. */
    bg_init();                          /* tabulate the per-x ridge heights */
    game_reset();
#if BLOCK_COLOUR_BARS
    draw_block_pattern();               /* fills buffer B (disp_buf = 0) */
#else
    draw_full_scene();                  /* fills buffer B (disp_buf = 0) */
#endif
    buf_swap_request();
    wait_disp(1);                       /* B is now scanned out */
#if BLOCK_COLOUR_BARS
    draw_block_pattern();               /* fills buffer A */
#else
    draw_full_scene();                  /* fills buffer A */
#endif
    /* Both buffers hold the scene and every write the firmware will ever make
       during the power-up fill has been issued, so the fabric's startup write
       bypass (top.v wr_armable) is idle from here on. The two blanked display
       frames let the read engine refill the video FIFO with clean data before
       the output is unblanked, so the first frame the monitor can see is the
       composed scene and not the tail of the bypass-contended read stream. */
    wait_frame();
    wait_frame();
    /* The scanned buffer is complete, so the fabric may stop blanking the HDMI
       output: the first FB_READY toggle also ends the write bypass. */
    apb_write(REG_FB_READY, 1u);
    sync_old_state();                   /* both buffers hold the scene: arm
                                           delta rendering from here on       */
    r = 0;                              /* A is rendered, ready to be shown */

#if STATIC_TEST
    /* No writes at all from here on: both buffers hold the identical full
       scene, and the loop below only performs the framebuffer flip. Any
       stripe / flicker seen on screen is therefore produced by the read /
       FIFO / swap / pixel-CDC path alone, with the M3 write traffic absent. */
    while (1) {
        buf_swap_request();
        wait_disp(r);
        r ^= 1;
    }
#else
    while (1) {
        /* waiting for the flip below paces the loop at one frame (60 Hz) */

        /* KEY3 resets - edge triggered + simple hold debounce */
        {
            uint32_t keys_now = apb_read(REG_KEY);
            uint32_t press_edge = (~keys_now) & prev_keys;
            prev_keys = keys_now;
            if (press_edge & KEY_RESET) {
                if (reset_hold == 0) {
                    game_reset();
                    reset_hold = 12;    /* ~0.2 s at 60 Hz */
                }
            }
            if (reset_hold) reset_hold--;
        }

        if (!game_over) {
            /* player 1 paddle (normal key control) */
            if (KEY_PRESSED(KEY_UP))
                p1_pos -= P1_STEP;
            if (KEY_PRESSED(KEY_DOWN))
                p1_pos += P1_STEP;
            if (p1_pos < 0) p1_pos = 0;
            if (p1_pos > PADDLE_MAX) p1_pos = PADDLE_MAX;

            /* AI (only when ball is on the right side) */
            if (ball_x > AI_REACT_X && vx > 0) {
                if (ball_y < p2_pos + 30)
                    p2_pos -= AI_STEP;
                else if (ball_y > p2_pos + 70)
                    p2_pos += AI_STEP;
                if (p2_pos < 0) p2_pos = 0;
                if (p2_pos > PADDLE_MAX) p2_pos = PADDLE_MAX;
            }

            /* The ball's dirty region is a constant cost now (two fixed 13x13
               rects), so extra ticks multiply its speed for free. */
            {
                int32_t t;
                for (t = 0; t < TICKS_PER_RENDER; t++)
                    game_tick();
            }
        } else {
            /* game over: blink the score (~0.53 Hz) */
            if (++blink_cnt >= 32) {
                blink_cnt = 0;
                digit_dim ^= 1;
            }
        }

        /* Publish the object positions. These four APB writes are the ONLY
           per-frame bus traffic the game produces: the fabric latches them at
           the frame boundary and overlays the ball/paddles in the pixel path,
           so they move at a clean 60 Hz with no HyperRAM write and no
           dependency on the vblank-only write window. */
        apb_write(REG_P1_Y,   (uint32_t)p1_pos);
        apb_write(REG_P2_Y,   (uint32_t)p2_pos);
        apb_write(REG_BALL_X, (uint32_t)ball_x);
        apb_write(REG_BALL_Y, (uint32_t)ball_y);

        /* rewrite dirty blocks in the off-screen buffer, then show it.
           The flip only happens on the next frame boundary, so the buffer
           being scanned out is never written to -> no tearing. In steady
           state render() finds nothing dirty (only a score change or a key
           change repaints anything), so the loop stays a clean 60 Hz. */
        render(r);
        buf_swap_request();
        if (!wait_disp(r)) {            /* flip missing: pace on the frame tick */
            flip_miss++;
            wait_frame();
        }
        r ^= 1;
    }
#endif /* STATIC_TEST */
}
