//============================================================================
// HYPER_RAM_CTRL - Gowin HyperRAM IP wrapper, 128-byte burst (32 x 32b)
//============================================================================
//
// Wraps the embedded Gowin "HyperRAM Memory Interface" IP
// (HyperRAM_Memory_Interface_Top) for the GW1NSR-4C: W956D8MKY 64Mbit die,
// single channel, 8-bit DQ, differential CK, CLK ratio 1:2.
//
// IP CONFIGURATION (must match the Gowin IP wizard!):
//   Memory Type   = W956x8MKY     Dq Width = 8     Psram Width = 8
//   Data Width    = 32            Addr Width = 22  CS/Mask = 1/4
//   Clock Type    = DIFFERENTIAL  Memory Clock = 63 MHz
//   Burst Mode    = 128_Bytes     Burst Num = 32
//
// User interface (all in the clk_out domain):
//   * One task moves 128 bytes = 32 x 32-bit words.
//   * WRITE: pulse ex_wr_req with ex_addr valid. The caller streams the 32
//     words on ex_wr_data: word 0 must be stable during the request cycle
//     (drive the pack RAM read address one cycle earlier), word 1 on the
//     next cycle, ..., word 31 thirty-one cycles later. The controller
//     registers each word on the clk_out edge and the IP captures the
//     command together with word 0 on the following cycle. busy stays high
//     for 32 data cycles plus a fixed commit wait (the IP has no done).
//   * READ: pulse ex_rd_req with ex_addr valid. The IP streams back 32
//     words as ex_rd_valid pulses (passthrough of rd_data_valid - they are
//     NOT assumed to be back-to-back), then ex_rd_done pulses. A timeout
//     guards against a permanent stall so the display can resync.
//
// ADDRESS UNIT: the HyperRAM CA bus addresses 16-bit half-words, so one
// 128-byte burst spans 64 address units. Step ex_addr by 64 per burst.
//
//============================================================================
`timescale 1ns / 1ps

module hyper_ram_ctrl (
    input  wire        sys_clock,       // IP reference clock = 27MHz board crystal (IP 'clk')
    input  wire        sys_reset_n,     // fabric reset
    input  wire        memory_clk,      // HyperRAM memory clock (63 MHz)
    input  wire        pll_lock,        // PLL lock
    input  wire        global_reset_n,  // fabric reset ANDed with pll_lock

    //------------------------- user interface (clk_out) ----------------------
    input  wire [21:0] ex_addr,         // burst start address (2-byte units)

    // write stream
    input  wire        ex_wr_req,       // pulse: start one 128-byte write
    input  wire [31:0] ex_wr_data,      // word 0 on req cycle, word k k cycles later
    output reg         ex_wr_done,      // pulse: write task complete

    // read stream
    input  wire        ex_rd_req,       // pulse: start one 128-byte read
    output wire        ex_rd_valid,     // 32 read-word pulses (not necessarily back-to-back)
    output wire [31:0] ex_rd_data,      // read word, valid with ex_rd_valid
    output reg         ex_rd_done,      // pulse: 32 words collected
    output wire        ex_rd_stall,     // pulse: this burst hit the stall timeout

    output reg         busy,            // task in progress (req ignored while high)
    output wire        init_calib,      // IP initialization done
    output wire        clk_out,         // IP user clock

    //--------------------------- physical pins -------------------------------
    output wire [0:0]  O_hpram_ck,
    output wire [0:0]  O_hpram_ck_n,
    inout  wire [0:0]  IO_hpram_rwds,
    inout  wire [7:0]  IO_hpram_dq,
    output wire [0:0]  O_hpram_cs_n,
    output wire [0:0]  O_hpram_reset_n
);

    //----------------------------------------------------------------------
    // IP user-side signals
    //----------------------------------------------------------------------
    wire [31:0] rd_data;
    wire        rd_data_valid;
    reg  [31:0] wr_data;
    reg  [21:0] addr;
    reg         cmd;
    reg         cmd_en;
    reg  [3:0]  data_mask;

    // 32 words per 128-byte burst
    localparam [5:0] WORDS_PER_BURST = 6'd32;
    localparam [5:0] WR_LAST_CYCLE   = 6'd63;  // 32 data + 32 commit-wait cycles
    localparam [9:0] RD_TIMEOUT      = 10'd400; // ~12.7 us @31.5 MHz guard

    //----------------------------------------------------------------------
    // FSM
    //----------------------------------------------------------------------
    localparam IDLE = 2'd0;
    localparam WR   = 2'd1;
    localparam RD   = 2'd2;

    reg [1:0]  state;
    reg [5:0]  cyc;          // write cycle counter / generic counter
    reg [5:0]  rv_cnt;       // collected read words
    reg [9:0]  rd_to;        // read-stall timeout
    reg        rd_pad;       // read-stall: zero-fill the rest of the burst

    //----------------------------------------------------------------------
    // Embedded HyperRAM IP
    //   Generated by the Gowin IP wizard, Burst Mode = 128_Bytes,
    //   Burst Num = 32, Clock Type = DIFFERENTIAL (has O_hpram_ck_n).
    //----------------------------------------------------------------------
    HyperRAM_Memory_Interface_Top u_hpram (
        .clk            (sys_clock),
        .memory_clk     (memory_clk),
        .pll_lock       (pll_lock),
        .rst_n          (sys_reset_n),
        .wr_data        (wr_data),
        .rd_data        (rd_data),
        .rd_data_valid  (rd_data_valid),
        .addr           (addr),
        .cmd            (cmd),
        .cmd_en         (cmd_en),
        .data_mask      (data_mask),
        .init_calib     (init_calib),
        .clk_out        (clk_out),
        .O_hpram_ck     (O_hpram_ck),
        .O_hpram_ck_n   (O_hpram_ck_n),
        .IO_hpram_dq    (IO_hpram_dq),
        .IO_hpram_rwds  (IO_hpram_rwds),
        .O_hpram_cs_n   (O_hpram_cs_n),
        .O_hpram_reset_n(O_hpram_reset_n)
    );

    //----------------------------------------------------------------------
    // FSM (clk_out domain)
    //
    // Command is registered on the IDLE -> task transition, so cmd_en is a
    // clean one-cycle pulse and never couples to the data/wait counters.
    //----------------------------------------------------------------------
    always @(posedge clk_out or negedge global_reset_n) begin
        if (!global_reset_n) begin
            state       <= IDLE;
            busy        <= 1'b0;
            ex_wr_done  <= 1'b0;
            ex_rd_done  <= 1'b0;
            cyc         <= 6'b0;
            rv_cnt      <= 6'b0;
            rd_to       <= 10'b0;
            rd_pad      <= 1'b0;
            wr_data     <= 32'b0;
            addr        <= 22'b0;
            cmd_en      <= 1'b0;
            cmd         <= 1'b0;
            data_mask   <= 4'b1111;
        end else if (init_calib) begin
            cmd_en     <= 1'b0;           // default: single pulse
            ex_wr_done <= 1'b0;
            ex_rd_done <= 1'b0;

            case (state)
                //---------------------------- IDLE -------------------------
                IDLE: begin
                    cyc    <= 6'b0;
                    rv_cnt <= 6'b0;
                    rd_to  <= 10'b0;
                    rd_pad <= 1'b0;
                    if (ex_wr_req) begin
                        state     <= WR;
                        busy      <= 1'b1;
                        addr      <= ex_addr;
                        wr_data   <= ex_wr_data; // word 0 latched on req cycle
                        cmd       <= 1'b1;
                        cmd_en    <= 1'b1;
                        data_mask <= 4'b0000;
                    end else if (ex_rd_req) begin
                        state     <= RD;
                        busy      <= 1'b1;
                        addr      <= ex_addr;
                        cmd       <= 1'b0;
                        cmd_en    <= 1'b1;
                        data_mask <= 4'b0000;
                    end
                end

                //---------------------------- WRITE ------------------------
                // Word 0 was latched on the request cycle. Words 1..31 are
                // latched on cycles 0..30 (the IP captures word k one cycle
                // after it is latched). Byte enables stay low through the
                // last word cycle, then a fixed commit wait completes the
                // 64-cycle task envelope.
                WR: begin
                    if (cyc < (WORDS_PER_BURST - 6'd1))
                        wr_data <= ex_wr_data;
                    if (cyc == (WORDS_PER_BURST - 6'd1))
                        data_mask <= 4'b1111;
                    if (cyc < WR_LAST_CYCLE) begin
                        cyc <= cyc + 6'b1;
                    end else begin
                        cyc         <= 6'b0;
                        data_mask   <= 4'b1111;
                        ex_wr_done  <= 1'b1;
                        busy        <= 1'b0;
                        state       <= IDLE;
                    end
                end

                //---------------------------- READ -------------------------
                // Collect exactly 32 valid words; rd_data_valid pulses may
                // have gaps (IP internal FIFO / refresh), so only valid
                // pulses advance the counter. Timeout prevents a deadlock.
                RD: begin
                    data_mask <= 4'b1111;
                    if (rd_pad) begin
                        // Stalled: keep the word COUNT exact by zero-filling the
                        // rest of the burst. The caller counts bursts (not
                        // words), so ending short would leave the frame one
                        // group short and permanently offset the pixel stream
                        // (4-byte word offset -> channel rotation).
                        rv_cnt <= rv_cnt + 6'b1;
                        if (rv_cnt == WORDS_PER_BURST - 6'd1) begin
                            rv_cnt     <= 6'b0;
                            rd_pad     <= 1'b0;
                            ex_rd_done <= 1'b1;
                            busy       <= 1'b0;
                            state      <= IDLE;
                        end
                    end else begin
                    if (rd_data_valid && rv_cnt < WORDS_PER_BURST)
                        rv_cnt <= rv_cnt + 6'b1;

                    if (rd_data_valid)
                        rd_to <= 10'b0;
                    else if (rd_to < RD_TIMEOUT)
                        rd_to <= rd_to + 10'b1;

                    if (rv_cnt == WORDS_PER_BURST - 6'd1 && rd_data_valid) begin
                        rv_cnt     <= 6'b0;
                        ex_rd_done <= 1'b1;
                        busy       <= 1'b0;
                        state      <= IDLE;
                    end else if (rd_to == RD_TIMEOUT) begin
                        rd_pad <= 1'b1;       // zero-fill to exactly 32 words
                        rd_to  <= 10'b0;
                    end
                    end
                end

                default: state <= IDLE;
            endcase
        end
    end

    // Read stream passthrough (only while a read is active)
    // Real data words, plus zero-fill padding when the IP stalled, so every
    // burst always delivers exactly 32 words.
    // One-cycle pulse the moment a read burst hits the stall timeout: the IP
    // delivered NO word for RD_TIMEOUT cycles (400 = ~12.7us). This is the
    // smoking gun for "the read path starves": every stall injects 32 zero
    // words into the video FIFO, i.e. a black chunk on screen plus ~432 cycles
    // of lost production. Counted and shown on screen (see top.v).
    assign ex_rd_stall = (state == RD) && !rd_pad && (rd_to == RD_TIMEOUT);

    assign ex_rd_valid = (state == RD) &&
                         (rd_pad || (rd_data_valid && (rv_cnt < WORDS_PER_BURST)));
    assign ex_rd_data  = rd_pad ? 32'b0 : rd_data;

endmodule
